/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.LOVList.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LOVLIST service. Represents a row in the &quot;LOV_LOVLIST&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ejada.LOVList.model.impl.LOVLISTModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ejada.LOVList.model.impl.LOVLISTImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LOVLIST
 * @generated
 */
@ProviderType
public interface LOVLISTModel extends BaseModel<LOVLIST> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lovlist model instance should use the {@link LOVLIST} interface instead.
	 */

	/**
	 * Returns the primary key of this lovlist.
	 *
	 * @return the primary key of this lovlist
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lovlist.
	 *
	 * @param primaryKey the primary key of this lovlist
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this lovlist.
	 *
	 * @return the ID of this lovlist
	 */
	public long getId();

	/**
	 * Sets the ID of this lovlist.
	 *
	 * @param Id the ID of this lovlist
	 */
	public void setId(long Id);

	/**
	 * Returns the en name of this lovlist.
	 *
	 * @return the en name of this lovlist
	 */
	@AutoEscape
	public String getEnName();

	/**
	 * Sets the en name of this lovlist.
	 *
	 * @param EnName the en name of this lovlist
	 */
	public void setEnName(String EnName);

	/**
	 * Returns the ar name of this lovlist.
	 *
	 * @return the ar name of this lovlist
	 */
	@AutoEscape
	public String getArName();

	/**
	 * Sets the ar name of this lovlist.
	 *
	 * @param ArName the ar name of this lovlist
	 */
	public void setArName(String ArName);

}