/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package test.model.impl;

import test.model.Greeting;

import test.service.GreetingLocalServiceUtil;

/**
 * The extended model base implementation for the Greeting service. Represents a row in the &quot;localizationTest_Greeting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GreetingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GreetingImpl
 * @see Greeting
 * @generated
 */
public abstract class GreetingBaseImpl
	extends GreetingModelImpl implements Greeting {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a greeting model instance should use the <code>Greeting</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			GreetingLocalServiceUtil.addGreeting(this);
		}
		else {
			GreetingLocalServiceUtil.updateGreeting(this);
		}
	}

}