/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package anb.ejada.DataTest.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TESTT service. Represents a row in the &quot;FOOTEST_TESTT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>anb.ejada.DataTest.model.impl.TESTTModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>anb.ejada.DataTest.model.impl.TESTTImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TESTT
 * @generated
 */
@ProviderType
public interface TESTTModel extends BaseModel<TESTT> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a testt model instance should use the {@link TESTT} interface instead.
	 */

	/**
	 * Returns the primary key of this testt.
	 *
	 * @return the primary key of this testt
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this testt.
	 *
	 * @param primaryKey the primary key of this testt
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this testt.
	 *
	 * @return the uuid of this testt
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this testt.
	 *
	 * @param uuid the uuid of this testt
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the test ID of this testt.
	 *
	 * @return the test ID of this testt
	 */
	public long getTestId();

	/**
	 * Sets the test ID of this testt.
	 *
	 * @param TestId the test ID of this testt
	 */
	public void setTestId(long TestId);

	/**
	 * Returns the data of this testt.
	 *
	 * @return the data of this testt
	 */
	@AutoEscape
	public String getData();

	/**
	 * Sets the data of this testt.
	 *
	 * @param Data the data of this testt
	 */
	public void setData(String Data);

}