/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ejada.LOVList.model.impl;

import com.ejada.LOVList.model.LOVLIST;
import com.ejada.LOVList.model.LOVLISTModel;
import com.ejada.LOVList.model.LOVLISTSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LOVLIST service. Represents a row in the &quot;LOV_LOVLIST&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LOVLISTModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LOVLISTImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LOVLISTImpl
 * @generated
 */
@JSON(strict = true)
public class LOVLISTModelImpl
	extends BaseModelImpl<LOVLIST> implements LOVLISTModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lovlist model instance should use the <code>LOVLIST</code> interface instead.
	 */
	public static final String TABLE_NAME = "LOV_LOVLIST";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.BIGINT}, {"EnName", Types.VARCHAR},
		{"ArName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("EnName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ArName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LOV_LOVLIST (Id LONG not null primary key,EnName VARCHAR(75) null,ArName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table LOV_LOVLIST";

	public static final String ORDER_BY_JPQL = " ORDER BY lovlist.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY LOV_LOVLIST.Id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static LOVLIST toModel(LOVLISTSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LOVLIST model = new LOVLISTImpl();

		model.setId(soapModel.getId());
		model.setEnName(soapModel.getEnName());
		model.setArName(soapModel.getArName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<LOVLIST> toModels(LOVLISTSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LOVLIST> models = new ArrayList<LOVLIST>(soapModels.length);

		for (LOVLISTSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public LOVLISTModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LOVLIST.class;
	}

	@Override
	public String getModelClassName() {
		return LOVLIST.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LOVLIST, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LOVLIST, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LOVLIST, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((LOVLIST)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LOVLIST, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LOVLIST, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LOVLIST)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LOVLIST, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LOVLIST, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LOVLIST>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LOVLIST.class.getClassLoader(), LOVLIST.class, ModelWrapper.class);

		try {
			Constructor<LOVLIST> constructor =
				(Constructor<LOVLIST>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<LOVLIST, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LOVLIST, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LOVLIST, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LOVLIST, Object>>();
		Map<String, BiConsumer<LOVLIST, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LOVLIST, ?>>();

		attributeGetterFunctions.put("Id", LOVLIST::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<LOVLIST, Long>)LOVLIST::setId);
		attributeGetterFunctions.put("EnName", LOVLIST::getEnName);
		attributeSetterBiConsumers.put(
			"EnName", (BiConsumer<LOVLIST, String>)LOVLIST::setEnName);
		attributeGetterFunctions.put("ArName", LOVLIST::getArName);
		attributeSetterBiConsumers.put(
			"ArName", (BiConsumer<LOVLIST, String>)LOVLIST::setArName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _Id;
	}

	@Override
	public void setId(long Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@JSON
	@Override
	public String getEnName() {
		if (_EnName == null) {
			return "";
		}
		else {
			return _EnName;
		}
	}

	@Override
	public void setEnName(String EnName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_EnName = EnName;
	}

	@JSON
	@Override
	public String getArName() {
		if (_ArName == null) {
			return "";
		}
		else {
			return _ArName;
		}
	}

	@Override
	public void setArName(String ArName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ArName = ArName;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, LOVLIST.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LOVLIST toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LOVLIST>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LOVLISTImpl lovlistImpl = new LOVLISTImpl();

		lovlistImpl.setId(getId());
		lovlistImpl.setEnName(getEnName());
		lovlistImpl.setArName(getArName());

		lovlistImpl.resetOriginalValues();

		return lovlistImpl;
	}

	@Override
	public int compareTo(LOVLIST lovlist) {
		long primaryKey = lovlist.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LOVLIST)) {
			return false;
		}

		LOVLIST lovlist = (LOVLIST)object;

		long primaryKey = lovlist.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LOVLIST> toCacheModel() {
		LOVLISTCacheModel lovlistCacheModel = new LOVLISTCacheModel();

		lovlistCacheModel.Id = getId();

		lovlistCacheModel.EnName = getEnName();

		String EnName = lovlistCacheModel.EnName;

		if ((EnName != null) && (EnName.length() == 0)) {
			lovlistCacheModel.EnName = null;
		}

		lovlistCacheModel.ArName = getArName();

		String ArName = lovlistCacheModel.ArName;

		if ((ArName != null) && (ArName.length() == 0)) {
			lovlistCacheModel.ArName = null;
		}

		return lovlistCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LOVLIST, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LOVLIST, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LOVLIST, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LOVLIST)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LOVLIST, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LOVLIST, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LOVLIST, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LOVLIST)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LOVLIST>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _Id;
	private String _EnName;
	private String _ArName;

	public <T> T getColumnValue(String columnName) {
		Function<LOVLIST, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LOVLIST)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("EnName", _EnName);
		_columnOriginalValues.put("ArName", _ArName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("EnName", 2L);

		columnBitmasks.put("ArName", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LOVLIST _escapedModel;

}